### ISSUE TITLE
v2.0.3: kern.log is empty when sysklogd boot by systemd 

### ISSUE THREAD

**Issue by YanfeiXu** [troglobit/sysklogd#14]
version: sysklogd v2.0.3
conditions: use systemd to boot sysklogd on x86_64
result: kern.log is empty, and it will work rightly after restarting klogd manually.

I found klogd and syslogd's type has been change to simple from forking in xx.service. That causes klogd start to run atfer syslogd in about 15ms and it was hundreds ms before this change. I wonder if the short time cause kern.log empty and this args "--with-klogd-delay=SEC"  is especially for this issue?

**Comment by troglobit** [comment]
Yes, you should definitely configure sysklogd `--with-klogd-delay=SEC` if you want to use `klogd`. Use something safe, like 5 seconds.  However, considering that `klogd` has been removed in v2.1, I'd recommend `--without-klogd` and run just `syslogd` on your system since it has native support for kernel logging as of v2.0.

**Comment by YanfeiXu** [comment]
OK. Thanks for your suggestion!
