### ISSUE TITLE
Remote kernel log message are mapped to uucp facility in local log files

### ISSUE THREAD

**Issue by dale-email** [troglobit/sysklogd#32]
As per title, when using sysklogd 2.2.2, kernel messages from one machine are ending up being logged against the uucp facility on the other.  tcpdump shows that the traffic on the wire is correctly tagged with facility 0 so its an issue in the receiving sysklogd.

**Comment by troglobit** [comment]
This may be because we want to prevent regular users from spoofing kernel log messages. 

Thank you for reporting this.  I'll get some time over the weekend to look into a new patch release.

**Comment by dale-email** [comment]
I think that the messages should end up in the "user" facility when the receiving syslogd isn't started with the -k flag (as per the manual pages), but not "uucp".  I haven't checked to see whether adding -k puts them in the right place

**Comment by troglobit** [comment]
Yeah definitely not in the uucp facility.  Kernel should be reserved for the local kernel, I think.  So user is the least worst alternative.

Interesting, I'd forgotten about `-k`.  I think I resync'ed that with the FreeBSD syslogd.   What it does is set the following flag, so that definitely looks promising:

```

static int        KeepKernFac;            /* Keep remotely logged kernel facility */

```

If you could test that, I'd be most grateful! <3
