### ISSUE TITLE
-v option doesn't work as described in the man-page

### ISSUE THREAD

**Issue by fjaell** [troglobit/sysklogd#35]
syslogd(8) says that the -v option enables verbose logging. That doesn't work:

`# /usr/sbin/syslogd -v`
`syslogd v2.2.3`
`# pgrep syslogd`

syslogd prints the version string but doesn't start. 
Tested with both, 2.2.2 and 2.2.3

**Comment by troglobit** [comment]
Interesting, thank you for taking the time to report this!

Not immediately clear to me how we should fix this. On the one hand the binary behaves like the pre 2.0 sysklogd project, which might be what users expect, but one the other hand, since v2.0 I've tried to steer the projects towards being more like the original BSD syslogd, with inspirations from both FreeBSD and NetBSD (they have both strong suits but have very different feature sets.) For the command line I went with the FreeBSD style, which is where [the man page](https://www.unix.com/man-page/FreeBSD/8/SYSLOGD/) was merged from.

I think the best way is to first let the man page reflect what the binary does, then possibly migrate to the FreeBSD behavior in a later major release.  What do you think about that approach?

**Comment by fjaell** [comment]
That's fine for me.

**Comment by concatime** [comment]
Ideally, `-v` (same as `--verbose`) would be for verbosity and `-V` (uppercase, same as `--version`) for versioning as described in http://catb.org/~esr/writings/taoup/html/ch10s05.html. gzip and pigz are two examples of this behavior.

**Comment by troglobit** [comment]
@concatime well, ideal worlds do not exist, we can only strive to find the best compromise possible in any given situation. It's of course different when starting from a clean slate.  Either way, I stand by the decision above.

Also, please be aware that ESR is often not the person you want to go around quoting.
