### ISSUE TITLE
Large delay before /dev/log is created on startup

### ISSUE THREAD

**Issue by katp32** [troglobit/sysklogd#55]
In some cases (although maybe this is the behaviour everywhere?), it can take up to five whole seconds before `/dev/log` is opened. This poses a significant issue, as the entire init system has to stop and wait for syslogd, otherwise log messages from other services will be dropped.

I'm not entirely certain what the circumstances for this are. Some things improve startup time (such as compiling with `-O3`, which suggests that it's not just getting hung up on a timer), while other seemingly unrelated things cause startup time to drastically increase (startup takes about four seconds longer if the system hostname is set to anything other than an empty string).

For reference as to the performance relative to the rest of the system, the testing VM I used is able to start  all services in under a quarter of a second of syslogd is disabled. If the user is quick at typing, they can boot and log in well before syslogd has opened the socket. It's by far the largest bottleneck to boot time.

Also worth noting that in my tests, log files were being written to a tmpfs, which means this is not disk speed causing a bottleneck.

**Comment by troglobit** [comment]
Hi! 

Maybe you can tell us a little bit more about your system. Like what distribution you're on, the version of sysklogd you are using and your configuration? If we cannot reproduce your issue it'll be very difficult for us to help you out.

There are many things that may cause problems like these; big kernel log, name resolution delays, etc. 

Thank you
 /Joachim

**Comment by katp32** [comment]
It's a custom embedded system, not a mainstream distro, but I'm happy to provide any information that would be helpful.

I'm running sysklogd 2.3.0, invoked with `/sbin/syslogd -Fss`. At the point where syslogd is started, all network interfaces haven't even been brought up yet. The kernel log is 284 lines, or 23KiB on disk. Disabling logging of messages from the kern facility does not impact startup time.

At the time syslogd is started, it is the *only* running process on the system apart from init; the only setup done prior to starting syslogd is mounting filesystems and setting the hostname.

**Comment by troglobit** [comment]
OK, that's quite similar to how I've set up sysklogd to start in Buildroot.  For details, see: https://github.com/buildroot/buildroot/tree/master/package/sysklogd -- there is both a systemd unit file and a SysV init script there.

I've not got much experience running sysklogd under systemd, but I guess that's what you're using since your system is waiting for `/dev/log`?  Personally I use Finit, which instead waits for `/var/run/syslogd.pid` to be created (which is after `/dev/log` has been created), as a signal to the rest of the system that syslogd is ready.

Unfortunately I've never seen or got reports of anything similar to what you describe, and last night (CET) I just mentioned a few examples that could cause syslogd to wait/timeout interacting with the system.  There is a way to debug syslogd, by starting it with the `-d` command line flag to see what it does -- however, that requires also confirming this action by sending SIGUSR1 to the process, which in your case would be difficult.

In you shoes I'd probably start from `main()` in `syslogd.c` and work my way through to the last line of `init()`, where `/dev/log` is created to figure out what may be missing or wrong on my system.  It's not an awful lot of code to go through, but if you're not familiar with C it could of course be a bit discouraging.

I'll just mention a few other gotchas I've learned over the years:

  1. Check `/etc/hostname` and `/etc/hosts`, I keep a single-word hostname, e.g. `foo`, and have a dummy hosts line to match, e.g. `127.0.1.1  foo`
  2. I use the kernel devtmpfs to get a working `/dev`, along with `mdev` and `mdev -s` on startup, ymmv
  3. When I get weird behavior with `syslogd` I usually revert to no /etc/syslogd.conf` and then add line by line to see where it gets stuck or misbehaves.  Do you have any special setup in that file?
  4. Make sure all file systems are mounted properly before starting syslogd, e.g., you at least need a readable `/etc`, a writable `/var/log` and `/var/run`
  5. My `/var/log` is usually a `tmpfs`, but with a an actual backing store you could get initial delays when creating files, e.g. jffs2

**Comment by katp32** [comment]
The init system is custom, not systemd. It effectively just runs commands in sequence, and monitors processes for errors. Indeed, I am waiting for `/dev/log` to be created as a signal that syslogd is ready (would it be better to wait for `/run/syslogd.pid`?).

1. `/etc/hosts` only contains two entries, `127.0.1.1 localhost` and `::1 localhost`, and the system hostname is only 6 characters.
2. I am indeed using devtmpfs. No mdev, though.
3. I have `/etc/syslogd.conf` configured to write notice level messages for most facilities to per-facility log files (kern.log, auth.log, daemon.log, etc), and write all other notice level messages to `/var/log/messages`. I would assume this is not an unusual setup.
4. All filesystems are mounted correctly; this is the very first thing the system does, before starting syslogd.
5. The entire root filesystem is a tmpfs in this setup.

I'll take a look at the code to try to figure out what's going on. Thanks for the help so far.

**Comment by katp32** [comment]
After doing some tests with the code, it seems the delay occurs when calling gethostbyname(3) in init, which would at least suggest that this is not a sysklogd issue.
