### ISSUE TITLE
runstatedir is not defined in autoconf version 2.69

### ISSUE THREAD

**Issue by fjaell** [troglobit/sysklogd#6]
latest released version of autoconf is 2.69 and does not define "runstatedir" which was added with commit

http://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=commit;h=a197431414088a417b407b9b20583b2e8f7363bd

to autoconf after the 2.69 release. Running autoreconf on the sysklogd sources gives a broken source tree therefore.

Thanks.

**Comment by troglobit** [comment]
I'm just realizing the autoconf project has not made an official release since 2012 ... :flushed: 

I'm using Ubuntu and Debian, where this seems to be supported.  The sysklogd patch idea originally came fro Gentoo.  So what system are you using?

Not sure how I should approach this bug report atm.

**Comment by troglobit** [comment]
As a background.  The change in sysklogd configure.ac came about due to Gentoo using `--localstatedir=/var/lib` for all (?) configure based applications and sysklogd <2.0.1 simply appended `/run` to that, which on most systems works flawlessly since they set it to `/var` instead.  I had my reservations but since `--runstatedir` worked on Gentoo and also on Debian & Ubuntu I went ahead with the change.  I guess I could add more complexity to `configure.ac` but I'd much rather avoid that ... any ideas?

Original report is here https://bugs.gentoo.org/701048

**Comment by fjaell** [comment]
As far as I can see gentoo solves the problem in the above bug-report differently and not by using --runstatedir because they don't use a autoconf with --runstatedir added.
Using /var/lib for --localstatedir seems wrong to me, though.
I'm using CRUX with a stock autoconf 2.69, a quick search shows me that arch, SUSE and LFS didn't patch autoconf for --runstatedir either.

My suggestion would be to revert the change or at least use $localstatedir/run for the PID location if runstatedir is not defined/used.

**Comment by troglobit** [comment]
Thanks for the feedback, will look into it as soon as possible!

**Comment by troglobit** [comment]
Should be fixed on master now, please let me know otherwise so we can reopen this issue.  Thanks again for the report!

**Comment by fjaell** [comment]
Yep, that works. Thanks a lot!

**Comment by troglobit** [comment]
Great, thank you for verifying! 😃
