### ISSUE TITLE
Add support for -c to disable "last message repeated"

### ISSUE THREAD

**Issue by lafibre** [troglobit/sysklogd#61]
Hello.
Is there a way to disable the "last repeated message" as old sysklogd did ?

`       -c     Disable the repeating line compression that normally suppresses the repeated lines and logs a message such as 'last message repeated 124 times'.  With this option, all repeated lines will be logged.`

thanks !

**Comment by troglobit** [comment]
Not at the moment.

When I adopted sysklogd the goal was to integrate RFC5424 support, among other things.  In the v2.0 release cycle this was done by evicting a lot of the old code to; 1) be able to drop the GPL license, 2) sync with the FreeBSD original.  In that process we lost a lot of features, and a full sync was not possible, so some of the old features had to be dropped.

Since [FreeBSD syslogd has the `-c` option](https://man.freebsd.org/cgi/man.cgi?syslogd), so we should re-add it for the next release.

**Comment by troglobit** [comment]
Please note, compared to old sysklogd, the new `-c` option has to be supplied twice to apply to regular files.  By default a single `-c` means disabling log compression for pipes.

**Comment by opty77** [comment]
@troglobit: Don't you actually disable the `last message buffered x times`? (At least if you're not debugging.)

**Comment by troglobit** [comment]
Yes, that's what log compression means in the upstream BSDs that sysklogd aims to track.
